tasks:
  - name: Script Task
    init: echo 'npm install' # This runs during prebuild to install dependencies
    command: |
      cd ./client  # Navigate to the client directory
      npm install  # Ensure npm dependencies are installed in the client folder
      npm start    # Start the frontend application

# List the ports to expose
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview